// src/windows/home/Home.jsx
import './Home.css';
import { useState } from 'react';
import logo from '../../assets/logo.png';
import Projects from './Projects';
import { add } from '../../icons';
import ChooseArchitect from './ChooseArchitect';
import { Info } from '../dialog/dialogs';

function Home() {

  const [projectType, selectProjectType] = useState('world');

  const [chooseArchitect, setChooseArchitect] = useState(false);

  return (
    <div className='background' id='home'>
      <div id='navigation'>
        <div className='glow' id='credit-label'>
          <img id='logo' src={logo}></img>
          <div>
            <h3 style={{margin: 0}}>Beaver Architect</h3>
            <span style={{fontSize: '14px'}}><em>By Millenniar</em></span>
          </div>
        </div>
        <div style={{margin: '60px 10px 30px 10px', cursor: 'pointer'}} className='decorated-label' onClick={() => setChooseArchitect(true)}>
          <div className='decorated-icon glow'>
            <img src={add}/>
          </div>
          <span style={{fontSize: '18px', fontWeight: '500'}}>New Project</span>
        </div>
        <div style={{padding: '20px'}}>
          <button className={projectType === 'world' ? 'selected' : 'unselected'} onClick={() => selectProjectType('world')}>Worlds</button>
          <button className={projectType === 'structure' ? 'selected' : 'unselected'} onClick={() => selectProjectType('structure')}>Structures</button>
          <button className={projectType === 'terrain' ? 'selected' : 'unselected'} onClick={() => selectProjectType('terrain')}>Layers</button>
          <hr style={{margin: '15px 30px'}}></hr>
          <button className={projectType === 'data_pack' ? 'selected' : 'unselected'} onClick={() => selectProjectType('data_pack')}>Data Packs</button>
        </div>
      </div>
      <div className='foreground' id='projects'>
        <Projects type={projectType} setChooseArchitect={setChooseArchitect} />
      </div>
      {chooseArchitect && <ChooseArchitect close={() => setChooseArchitect(false)}/>}
    </div>
  );
}

export default Home;

// src/app/home/home/home.component.ts
import { NgClass, NgFor, NgIf } from '@angular/common';
import { Component, Input } from '@angular/core';
import { ProjectsComponent } from "../projects/projects.component";
import { EditProjectComponent } from "../edit-project/edit-project.component";
import { Project } from '../../../types';
import { ElectronService } from 'ngx-electron';

@Component({
  selector: 'home',
  standalone: true,
  imports: [NgClass, NgFor, NgIf, ProjectsComponent, EditProjectComponent],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent {

  constructor(private electron: ElectronService) { }

  @Input() type?: string

  @Input() interactive: HomeInteractive = HomeInteractive.PROJECTS

  isSelectedType(type: string): boolean {
    return this.type == type
  }

  selectType(type: string): void {
    if(this.interactive === HomeInteractive.PROJECTS) {
      this.type = this.type === type ? undefined : type
    }
  }

  newProject() {
    this.interactive = HomeInteractive.NEW_PROJECT
    this.type = this.type ?? 'world'
  }

  editProject?: Project

  doEditProject(project: Project) {
    this.editProject = project
    this.changeInteractive(HomeInteractive.EDIT_PROJECT)
  }

  changeInteractive(interactive: HomeInteractive) {
    this.interactive = interactive
  }

  openSettings() {
    this.electron.ipcRenderer.invoke('settings:open')
  }
}

export enum HomeInteractive {

  PROJECTS = 'projects',
  NEW_PROJECT = 'new_project',
  EDIT_PROJECT = 'edit_project'
}
<div class="bg-back-1 flex h-full">

  <div class="w-64 flex flex-col gap-6 py-5 pr-1 pl-4">
    <div class="glow flex after:bg-back-2 after:rounded-2xl">
      <img class="w-[70px] h-[70px]" src="assets/logo.png">
      <div class="py-2">
        <h3 class="text-lg font-semibold">Beaver Architect</h3>
        <em class="text-sm">By Millenniar</em>
      </div>
    </div>
    <div class="decorated-label py-2 pt-14 pb-8 cursor-pointer" (click)="newProject()">
      <div class="decorated-icon glow">
        <img src="assets/icon/add.svg">
      </div>
      <span class="text-lg font-semibold">New Project</span>
    </div>

    <div class="p-5 flex flex-col gap-3">
      <button class="type-selector"
        [ngClass]="{'selected': isSelectedType('world'), 'unselected': !isSelectedType('world')}"
        (click)="selectType('world')">Worlds</button>
      <button class="type-selector"
        [ngClass]="{'selected': isSelectedType('structure'), 'unselected': !isSelectedType('structure')}"
        (click)="selectType('structure')">Structures</button>
      <button class="type-selector"
        [ngClass]="{'selected': isSelectedType('terrain'), 'unselected': !isSelectedType('terrain')}"
        (click)="selectType('terrain')">Terrains</button>
      <button class="type-selector"
        [ngClass]="{'selected': isSelectedType('biome'), 'unselected': !isSelectedType('biome')}"
        (click)="selectType('biome')">Biomes</button>
      <hr class="my-4 mx-7">
      <button class="type-selector"
        [ngClass]="{'selected': isSelectedType('data_pack'), 'unselected': !isSelectedType('data_pack')}"
        (click)="selectType('data_pack')">Data Packs</button>
    </div>

    <div class="grow"></div>
    <div class="ml-3 mb-2 flex gap-3">
      <img class="w-1/2" src="assets/credit/millenniar_title.svg">
      <div class="grow"></div>
      <button (click)="openSettings()">
        <i class="pi pi-cog text-lg text-fore-3"></i>
      </button>
    </div>
  </div>

  <projects *ngIf="interactive === 'projects'" class="home-interactive" [type]="type" (editProject)="doEditProject($event)"></projects>
  <edit-project *ngIf="interactive === 'new_project'" class="home-interactive" [type]="type ?? 'world'" (changeInteractive)="changeInteractive($event)"></edit-project>
  <edit-project *ngIf="interactive === 'edit_project'" class="home-interactive" [isNew]="false" [type]="editProject!.type" [project]="editProject!" (changeInteractive)="changeInteractive($event)"></edit-project>
</div>
